name: Terraform PR

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

env:
  TF_CLOUD_ORGANIZATION: eks-bootcamp-org
  TF_WORKSPACE: lifecycle-devint-cli
  TF_TOKEN_app_terraform_io: ${{ secrets.HCP_TERRAFORM_TOKEN }}

defaults:
  run:
    working-directory: environments/devint  

jobs:
  terraform-pr:
    name: Terraform PR Plan
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.4

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Trigger HCP Terraform Plan
        run: |
          terraform plan